id: A707FA841
base_file: fDAEC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:12:55.874887
  last_modified_at: 2022-06-11 13:12:55.874891
